### ISSUE TITLE
Ponder option does not work.

### ISSUE THREAD

**Issue by OmerFarukTutkun** [MichaeltheCoder7/Supernova#1]
Supernova always ponders even if I use "setoption name Ponder value false".

**Comment by MichaeltheCoder7** [comment]
Please check if you enabled ponder setting in the GUI. Per UCI protocol, only the GUI can activate pondering. The engine option does not do anything. It is only there to let the GUI know Supernova can ponder.

Also, Supernova prints "bestmove () ponder ()" every turn, but it is only providing information and not necessarily pondering.

**Comment by OmerFarukTutkun** [comment]
I thought that it was pondering since it prints bestmove and ponder. If it doesn't ponder, no problem I can use it for testing my own engine.
